### ISSUE TITLE
Build broken

### ISSUE THREAD

**Issue by lociii** [lociii/homeassistant-config#14]
Reason: https://github.com/home-assistant/home-assistant/issues/24720

Build breaks on travis, however config is working fine and can be successfully checked locally

**Comment by CCOSTAN** [comment]
I am seeing this issue as well. 

https://travis-ci.org/CCOSTAN/Home-AssistantConfig/jobs/559689872#L576-L577

**Comment by lociii** [comment]
Travis build removed. No plans to add it back for now.
