### ISSUE TITLE
Consider Shelly as a digitalstrom replacement

### ISSUE THREAD

**Issue by lociii** [lociii/homeassistant-config#23]
**Shelly 1**
Tasmota template: https://templates.blakadder.com/shelly_1.html

**Shelly 1PM**
Tasmota template: https://templates.blakadder.com/shelly_1PM.html
ESPHome template: https://community.home-assistant.io/t/shelly-1pm/118929/19
Consider resolder for V and A https://github.com/arendst/Tasmota/issues/5716#issuecomment-589879170

**Shelly 2.5**
Tasmota template: https://templates.blakadder.com/shelly_25.html
ESPHome template: https://www.die-welt.net/2020/04/controlling-roller-shutters-using-a-shelly-25-esphome-and-home-assistant/

**Shelly RGBW2**
Tasmota template: https://templates.blakadder.com/shelly_RGBW2.html

**Comment by lociii** [comment]
**Shelly i3**
Replacement for the wall switch terminal blocks.
To be released, No information about internals or open firmware yet
https://shelly.cloud/products/shelly-i3-smart-home-automation-device/

**Comment by lociii** [comment]
Progress report:
* Shelly 1 working great as a GE-KM200 replacement :heavy_check_mark: 
* Shelly i3 waiting to be flashed as a SW-TKM200 replacement :hourglass_flowing_sand: 
* Shelly 2.5 waiting to be flashed as a GR-KL200 and SW-UMR200 replacement :hourglass_flowing_sand:

**Comment by lociii** [comment]
Progress report:
* Shelly 1 working great as a GE-KM200 replacement :heavy_check_mark: 
* Shelly i3 not working properly yet with ESPHome as a SW-TKM200 replacement :hourglass_flowing_sand: 
* Shelly 2.5 used as a SW-TKM200 replacement :heavy_check_mark: 
  * Can be mounted easier than a Shelly i3 because it has no fixed cables attached
* Shelly 2.5 waiting to be flashed as a GR-KL200 and SW-UMR200 replacement :hourglass_flowing_sand:

**Comment by matejzero** [comment]
Could you post GPIO mappings for i3 when you have it? I'm waiting for my i3 and I just discovered ESPHome and love it.

I have Shelly1 running on ESPHome and RGBW2 in the works. RGBW2 works as a normal RGBW2 dimmer, but there are a few things I want to add such as dimming via momentary button press like Fibaro and figure out power consumption reads from A0 pin.

**Comment by lociii** [comment]
@matejzero sure. Here we go.

![i3_back](https://user-images.githubusercontent.com/366967/88367061-1bdf7900-cd8b-11ea-8149-ff514943a9d5.jpg)
![i3_front](https://user-images.githubusercontent.com/366967/88367064-1d10a600-cd8b-11ea-9c83-19bfbe358ae6.jpg)

**Comment by lociii** [comment]
IN1 -> GPIO 13
IN2 -> GPIO 14
IN3 -> GPIO 12

**Comment by lociii** [comment]
The problem with the i3 currently is that the input seems to be floating ON/OFF and no pullup or nothing that I tried worked out.
Either no input or always floating on/off.
I'll now waste some more money and use 2.5s instead of the i3 as they're even more flexible without the hard-wired cables.

**Comment by matejzero** [comment]
Thanks for the feedback. Too bad, I was really hoping i3 would work as it could solve most of my problems and the added input compared to 2.5 is great because of space problem.

I'll see what I can do with i3. Did it work OK with native firmware?

**Comment by lociii** [comment]
> I'll see what I can do with i3. Did it work OK with native firmware?

Never tried with default firmware as I wouldn't run it with MQTT anyway. But as with all the other Shelly products, I would expect it to run properly on default firmware.

I'm also pretty sure there will be a way to get it working with ESPHome. It's just way beyond my level of experience.
Maybe wait a few weeks until some of the core ESPHome people got their hands on this brand new device.

**Comment by lociii** [comment]
Six devices to go:
* Garden shed water control (2x 2.5)
* Guestroom ceiling light (1x 2.5)
* Bedroom ceiling light (1x 2.5)
* Hallway lights (2x RGBW2)

**Comment by lociii** [comment]
Conversion done!
